framework:
    workflows:
        order_workflow:
            type: 'state_machine' # Or 'state_machine' if your logic strictly follows state machine semantics
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Order
            places:
                - draft
                - pending
                - accepted
                - declined
                - notified
                - published
                - ready
                - hold
            transitions:
                create:
                    from: draft
                    to: pending
                accept:
                    from: pending
                    to: accepted
                decline:
                    from: pending
                    to: declined
                notify:
                    from: accepted
                    to: notified
                ready:
                    from: notified
                    to: ready
                hold:
                    from: ['draft','pending','accepted','notified','published']
                    to: hold
                publish:
                    from: notified
                    to: published
                revert:
                    from: ['pending','hold']
                    to: draft
