<?php

namespace ContainerULd2epz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JffWaSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jffWaS_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jffWaS_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\IndexController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\OrderController::acceptOrder' => ['privates', '.service_locator.uga7QBb', 'get_ServiceLocator_Uga7QBbService', true],
            'App\\Controller\\OrderCrudController::delete' => ['privates', '.service_locator.EDFwMy7', 'get_ServiceLocator_EDFwMy7Service', true],
            'App\\Controller\\OrderCrudController::edit' => ['privates', '.service_locator.EDFwMy7', 'get_ServiceLocator_EDFwMy7Service', true],
            'App\\Controller\\OrderCrudController::index' => ['privates', '.service_locator.4n4ylFv', 'get_ServiceLocator_4n4ylFvService', true],
            'App\\Controller\\OrderCrudController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\OrderCrudController::show' => ['privates', '.service_locator.ruxHxcA', 'get_ServiceLocator_RuxHxcAService', true],
            'App\\Controller\\OrderReviewMakerController::index' => ['privates', '.service_locator.4n4ylFv', 'get_ServiceLocator_4n4ylFvService', true],
            'App\\Controller\\OrderReviewMakerController::show' => ['privates', '.service_locator.ruxHxcA', 'get_ServiceLocator_RuxHxcAService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\IndexController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\OrderController:acceptOrder' => ['privates', '.service_locator.uga7QBb', 'get_ServiceLocator_Uga7QBbService', true],
            'App\\Controller\\OrderCrudController:delete' => ['privates', '.service_locator.EDFwMy7', 'get_ServiceLocator_EDFwMy7Service', true],
            'App\\Controller\\OrderCrudController:edit' => ['privates', '.service_locator.EDFwMy7', 'get_ServiceLocator_EDFwMy7Service', true],
            'App\\Controller\\OrderCrudController:index' => ['privates', '.service_locator.4n4ylFv', 'get_ServiceLocator_4n4ylFvService', true],
            'App\\Controller\\OrderCrudController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\OrderCrudController:show' => ['privates', '.service_locator.ruxHxcA', 'get_ServiceLocator_RuxHxcAService', true],
            'App\\Controller\\OrderReviewMakerController:index' => ['privates', '.service_locator.4n4ylFv', 'get_ServiceLocator_4n4ylFvService', true],
            'App\\Controller\\OrderReviewMakerController:show' => ['privates', '.service_locator.ruxHxcA', 'get_ServiceLocator_RuxHxcAService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.e_4zbH4', 'get_ServiceLocator_E4zbH4Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.Mhqdd2r', 'get_ServiceLocator_Mhqdd2rService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\IndexController::index' => '?',
            'App\\Controller\\OrderController::acceptOrder' => '?',
            'App\\Controller\\OrderCrudController::delete' => '?',
            'App\\Controller\\OrderCrudController::edit' => '?',
            'App\\Controller\\OrderCrudController::index' => '?',
            'App\\Controller\\OrderCrudController::new' => '?',
            'App\\Controller\\OrderCrudController::show' => '?',
            'App\\Controller\\OrderReviewMakerController::index' => '?',
            'App\\Controller\\OrderReviewMakerController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\IndexController:index' => '?',
            'App\\Controller\\OrderController:acceptOrder' => '?',
            'App\\Controller\\OrderCrudController:delete' => '?',
            'App\\Controller\\OrderCrudController:edit' => '?',
            'App\\Controller\\OrderCrudController:index' => '?',
            'App\\Controller\\OrderCrudController:new' => '?',
            'App\\Controller\\OrderCrudController:show' => '?',
            'App\\Controller\\OrderReviewMakerController:index' => '?',
            'App\\Controller\\OrderReviewMakerController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
