<?php

namespace ContainerULd2epz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComplexPasswordValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\Constraints\ComplexPasswordValidator' shared autowired service.
     *
     * @return \App\Validator\Constraints\ComplexPasswordValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/src/Validator/Constraints/ComplexPasswordValidator.php';

        return $container->privates['App\\Validator\\Constraints\\ComplexPasswordValidator'] = new \App\Validator\Constraints\ComplexPasswordValidator();
    }
}
