<?php

namespace ContainerULd2epz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderWorkflowSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\OrderWorkflowSubscriber' shared autowired service.
     *
     * @return \App\EventListener\OrderWorkflowSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/OrderWorkflowSubscriber.php';

        return $container->privates['App\\EventListener\\OrderWorkflowSubscriber'] = new \App\EventListener\OrderWorkflowSubscriber(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
