<?php

namespace ContainerULd2epz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoCloudFlareControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VideoCloudFlareController' shared autowired service.
     *
     * @return \App\Controller\VideoCloudFlareController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/VideoCloudFlareController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/CloudflareStreamService.php';

        $container->services['App\\Controller\\VideoCloudFlareController'] = $instance = new \App\Controller\VideoCloudFlareController(new \App\Service\CloudflareStreamService());

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\VideoCloudFlareController', $container));

        return $instance;
    }
}
