<?php

namespace ContainerULd2epz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVideoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\VideoController' shared autowired service.
     *
     * @return \App\Controller\VideoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/VideoController.php';
        include_once \dirname(__DIR__, 4).'/src/Service/BunnyCDNStorageService.php';

        $container->services['App\\Controller\\VideoController'] = $instance = new \App\Controller\VideoController(new \App\Service\BunnyCDNStorageService($container->getEnv('BUNNYCDN_REGION'), $container->getEnv('BUNNYCDN_STORAGE_ZONE_NAME'), $container->getEnv('BUNNYCDN_ACCESS_KEY')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\VideoController', $container));

        return $instance;
    }
}
